{
  "url": "https://api.github.com/repos/dexfire/mathwiki_app_android/releases/12345600",
  "assets_url": "https://api.github.com/repos/dexfire/mathwiki_app_android/releases/12345600/assets",
  "upload_url": "https://uploads.github.com/repos/dexfire/mathwiki_app_android/releases/12345600/assets{?name,label}",
  "html_url": "https://github.com/dexfire/mathwiki_app_android/releases/tag/1",
  "id": 12345600,
  "node_id": "MDc6UmVsZWFzZTEyMzQ1NjAw",
  "tag_name": "1",
  "target_commitish": "master",
  "name": "1.0 Beta",
  "draft": false,
  "author": {
    "login": "dexfire",
    "id": 13636179,
    "node_id": "MDQ6VXNlcjEzNjM2MTc5",
    "avatar_url": "https://avatars2.githubusercontent.com/u/13636179?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/dexfire",
    "html_url": "https://github.com/dexfire",
    "followers_url": "https://api.github.com/users/dexfire/followers",
    "following_url": "https://api.github.com/users/dexfire/following{/other_user}",
    "gists_url": "https://api.github.com/users/dexfire/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/dexfire/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/dexfire/subscriptions",
    "organizations_url": "https://api.github.com/users/dexfire/orgs",
    "repos_url": "https://api.github.com/users/dexfire/repos",
    "events_url": "https://api.github.com/users/dexfire/events{/privacy}",
    "received_events_url": "https://api.github.com/users/dexfire/received_events",
    "type": "User",
    "site_admin": false
  },
  "prerelease": false,
  "created_at": "2018-08-10T09:26:12Z",
  "published_at": "2018-08-10T09:37:15Z",
  "assets": [
    {
      "url": "https://api.github.com/repos/dexfire/mathwiki_app_android/releases/assets/8198845",
      "id": 8198845,
      "node_id": "MDEyOlJlbGVhc2VBc3NldDgxOTg4NDU=",
      "name": "app-release.apk",
      "label": null,
      "uploader": {
        "login": "dexfire",
        "id": 13636179,
        "node_id": "MDQ6VXNlcjEzNjM2MTc5",
        "avatar_url": "https://avatars2.githubusercontent.com/u/13636179?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dexfire",
        "html_url": "https://github.com/dexfire",
        "followers_url": "https://api.github.com/users/dexfire/followers",
        "following_url": "https://api.github.com/users/dexfire/following{/other_user}",
        "gists_url": "https://api.github.com/users/dexfire/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dexfire/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dexfire/subscriptions",
        "organizations_url": "https://api.github.com/users/dexfire/orgs",
        "repos_url": "https://api.github.com/users/dexfire/repos",
        "events_url": "https://api.github.com/users/dexfire/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dexfire/received_events",
        "type": "User",
        "site_admin": false
      },
      "content_type": "application/vnd.android.package-archive",
      "state": "uploaded",
      "size": 2397456,
      "download_count": 1,
      "created_at": "2018-08-10T09:36:16Z",
      "updated_at": "2018-08-10T09:36:28Z",
      "browser_download_url": "https://github.com/dexfire/mathwiki_app_android/releases/download/1/app-release.apk"
    }
  ],
  "tarball_url": "https://api.github.com/repos/dexfire/mathwiki_app_android/tarball/1",
  "zipball_url": "https://api.github.com/repos/dexfire/mathwiki_app_android/zipball/1",
  "body": "The first **test** release, just for testing purpose, **nothing** implemented."
}